version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - pihole
    ports:
      - "80:80"      # HTTP entrypoint
      - "443:443"    # HTTPS (if you add certs later)
    volumes:
      - ./nginx/inshellgagici.conf.template:/etc/nginx/templates/inshellgagici.conf.template:ro
    environment:
      DOMAIN: "${DOMAIN}"
    networks:
      - web

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Amsterdam"
      FTLCONF_webserver_api_password: "${PIHOLE_WEBPASS}"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "${PIHOLE_DNS_UPSTREAMS}"
      FTLCONF_misc_etc_dnsmasq_d: "true"
      FTLCONF_misc_dnsmasq_lines: "address=/.${DOMAIN}/${HOST_IP}"
    volumes:
      - ${DATA_STORAGE_BASE_DIR}/pihole/etc-pihole:/etc/pihole
      - ${DATA_STORAGE_BASE_DIR}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - web
  
  filebrowser:
    image: filebrowser/filebrowser:v2-s6
    container_name: filebrowser
    restart: unless-stopped
    environment:
      FB_DATABASE: "/config/database.db"
      FB_ROOT: "/srv"
      FB_USERNAME: ${FB_USER}
      FB_PASSWORD: ${FB_PASS}
    volumes:
      - ${DATA_STORAGE_BASE_DIR}/filebrowser/nas-data:/srv
      - ${DATA_STORAGE_BASE_DIR}/filebrowser/config:/config
    networks:
      - web

networks:
  web:
    driver: bridge
