version: "3.8"

services:
  proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    depends_on:
      - pihole
    ports:
      - "80:80"      # HTTP entrypoint
      - "443:443"    # HTTPS (if you add certs later)
    volumes:
      - ./nginx/inshellgagici.conf.template:/etc/nginx/templates/inshellgagici.conf.template:ro
    environment:
      DOMAIN: "${DOMAIN}"
    networks:
      - web

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Amsterdam"
      FTLCONF_webserver_api_password: "${PIHOLE_WEBPASS}"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "${PIHOLE_DNS_UPSTREAMS}"
      FTLCONF_misc_etc_dnsmasq_d: "true"
      FTLCONF_misc_dnsmasq_lines: "address=/.${DOMAIN}/${HOST_IP}"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"   # DNS
      - "53:53/udp"
    networks:
      - web

networks:
  web:
    driver: bridge
