name: Deploy on Pi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64]
    environment: Production
    steps:
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER /home/paul/actions-runner/_work/ServerServices || true

      - uses: actions/checkout@v4

      - name: Prepare workspace directories
        run: |
          mkdir -p "$GITHUB_WORKSPACE/etc-dnsmasq.q" "$GITHUB_WORKSPACE/etc-pihole"
        
      - name: Write .env from secret
        env:
          ENV_FILE_B64: ${{ secrets.ENV_FILE_B64 }}
        run: |
          echo "$ENV_FILE_B64" | base64 -d > .env
          chmod 600 .env

      - name: Verify .env
        run: |
          if [[ ! -f .env ]]; then
            echo "❌ .env not found" && exit 1
          fi
          echo ".env exists, size: $(stat -c '%s' .env) bytes"
          echo "  → lines: $(wc -l < .env)"
          echo "  → keys:"
          cut -d= -f1 .env | sed 's/^/    - /'

      - name: Pull and restart containers
        working-directory: ${{ github.workspace }}
        run: |
          docker compose pull
          docker compose up -d --remove-orphans
